EventHandler Class Reference
The event handler determines, according to some user–specified rules, how to apply the different requests to the world.
#include <event_handler.h>
Public Member Functions
EventHandler (boost::shared_ptr< History > history, boost::shared_ptr< RobotControl > robot_control)
void handle_event (boost::shared_ptr< Event > event)
void register_listener (boost::shared_ptr< SimulationListener > listener)
void set_position_request_handler (boost::shared_ptr< VectorRequestHandler > position_request_handler)
void set_velocity_request_handler (boost::shared_ptr< VectorRequestHandler > velocity_request_handler)
void set_acceleration_request_handler (boost::shared_ptr< VectorRequestHandler > acceleration_request_handler)
void set_marker_request_handler (boost::shared_ptr< MarkerRequestHandler > marker_request_handler)
void set_type_change_request_handler (boost::shared_ptr< TypeChangeRequestHandler > type_change_request_handler)
Private Member Functions
void handle_look_event (boost::shared_ptr< LookEvent > look_event)
void handle_compute_event (boost::shared_ptr< ComputeEvent > compute_event)
void handle_handle_requests_event (boost::shared_ptr< HandleRequestsEvent > handle_requests_event)
void update_listeners (boost::shared_ptr< Event > event)
boost::shared_ptr< WorldInformation > extrapolate_old_world_information (int time)
Private Attributes
boost::shared_ptr< VectorRequestHandler > position_request_handler_
boost::shared_ptr< VectorRequestHandler > velocity_request_handler_
boost::shared_ptr< VectorRequestHandler > acceleration_request_handler_
boost::shared_ptr< MarkerRequestHandler > marker_request_handler_
boost::shared_ptr< TypeChangeRequestHandler > type_change_request_handler_
vector< boost::shared_ptr< SimulationListener > > listeners_
boost::shared_ptr< History > history_
boost::shared_ptr< RobotControl > robot_control_
int time_of_last_event_
Detailed Description
The event handler determines, according to some user–specified rules, how to apply the different requests to the world.
The abstract event handler class provides the following functionality: 1. handle compute and look event by delegation to RobotControl 2. partly handle HandleRequests events by extrapolating the robot positions and calling the request handlers 3. registering of simulation listeners and updating them when the world changes
In most cases a subclass of EventHandler should only define custom handle_request functions for the possible requests. If it does not provide a custom implementation for a particular handle_*_request method, a warning message is issued upon the occurrence of such a request.
Definition at line 51 of file event_handler.h.
Member Function Documentation
void EventHandler::handle_event (boost::shared_ptr< Event > event)
handles the given event. By calling appropriate handlers and updating the listeners.
Definition at line 37 of file event_handler.cc.
References handle_compute_event(), handle_handle_requests_event(), handle_look_event(), time_of_last_event_, and update_listeners().
void EventHandler::register_listener (boost::shared_ptr< SimulationListener > listener)
registers a new listener.
Definition at line 179 of file event_handler.cc.
void EventHandler::set_position_request_handler (boost::shared_ptr< VectorRequestHandler > position_request_handler) [inline]
setter for position request handler
Definition at line 72 of file event_handler.h.
References position_request_handler_.
void EventHandler::set_velocity_request_handler (boost::shared_ptr< VectorRequestHandler > velocity_request_handler) [inline]
setter for velocity request handler
Definition at line 79 of file event_handler.h.
void EventHandler::set_acceleration_request_handler (boost::shared_ptr< VectorRequestHandler > acceleration_request_handler) [inline]
setter for acceleration request handler
Definition at line 86 of file event_handler.h.
void EventHandler::set_marker_request_handler (boost::shared_ptr< MarkerRequestHandler > marker_request_handler) [inline]
setter for marker request handler
Definition at line 93 of file event_handler.h.
void EventHandler::set_type_change_request_handler (boost::shared_ptr< TypeChangeRequestHandler > type_change_request_handler) [inline]
setter for type change request handler
Definition at line 100 of file event_handler.h.
void EventHandler::handle_look_event (boost::shared_ptr< LookEvent > look_event) [private]
handles the given look event by delegating it to RobotControl
Definition at line 65 of file event_handler.cc.
Referenced by handle_event().
void EventHandler::handle_compute_event (boost::shared_ptr< ComputeEvent > compute_event) [private]
handles the given compute event by delegating it to RobotControl
Definition at line 71 of file event_handler.cc.
Referenced by handle_event().
void EventHandler::handle_handle_requests_event (boost::shared_ptr< HandleRequestsEvent > handle_requests_event) [private]
handles the given HandleRequests event by doing the following 1. producing a new WorldInformation object by extrapolating and handling requests 2. adding the new WorldInformation object to the history
Definition at line 83 of file event_handler.cc.
References extrapolate_old_world_information(), and position_request_handler_.
Referenced by handle_event().
void EventHandler::update_listeners (boost::shared_ptr< Event > event) [private]
informs all listeners after each event
Definition at line 183 of file event_handler.cc.
Referenced by handle_event().
boost::shared_ptr< WorldInformation > EventHandler::extrapolate_old_world_information (int time) [private]
generates a new WorldInformation object by extrapolating it from the newest old one to time t
Definition at line 138 of file event_handler.cc.
References WorldInformation::markers(), WorldInformation::obstacles(), WorldInformation::robot_data(), and WorldInformation::time().
Referenced by handle_handle_requests_event().
Member Data Documentation
boost::shared_ptr<VectorRequestHandler> EventHandler::position_request_handler_ [private]
Request Handlers. One for each type of request.
Definition at line 135 of file event_handler.h.
Referenced by handle_handle_requests_event(), and set_position_request_handler().
int EventHandler::time_of_last_event_ [private]
The time the last event has happened. Used to ensure correct ordering of events.
Definition at line 148 of file event_handler.h.
Referenced by handle_event().
The documentation for this class was generated from the following files:
src/EventHandlers/event_handler.h
src/EventHandlers/event_handler.cc