SimulationControl Class Reference
Controls the simulation.
#include <simulation_control.h>
Inherited by SampleControl.
Public Member Functions
void create_new_simulation (const std::string &configuration_filename, std::size_t history_length)
void start_simulation ()
void pause_simulation ()
void terminate_simulation ()
void process_simulation ()
void set_visualizer (boost::shared_ptr< Visualizer > visualizer)
Private Member Functions
double compute_new_processing_time ()
Private Attributes
double processing_time_factor_
double current_processing_time_
boost::posix_time::ptime last_process_simulation_time_
boost::shared_ptr< WorldInformation > current_world_information_
boost::shared_ptr< WorldInformation > next_world_information_
boost::shared_ptr< History > history_
boost::shared_ptr< SimulationKernelFunctor > simulation_kernel_functor_
boost::thread simulation_thread_
boost::shared_ptr< Visualizer > visualizer_
Classes
class SimulationKernelFunctor
Detailed Description
Controls the simulation.
The class SimulationControl provides code to set up a new simulation (and cleanup any old one) as well as start/pause/terminate the Simulation–Thread. Furthermore it provides a method called process simulation that is responsible for consuming the history’s elements according to the Processing–Time.
Author: Daniel Wonisch
Definition at line 30 of file simulation_control.h.
Member Function Documentation
void SimulationControl::create_new_simulation (const std::string & configuration_filename, std::size_t history_length)
cleans up the old simulation and creates a new one without starting it.
Definition at line 24 of file simulation_control.cc.
References terminate_simulation().
void SimulationControl::start_simulation ()
starts the simulation
Definition at line 51 of file simulation_control.cc.
References SimulationControl::SimulationKernelFunctor::loop().
void SimulationControl::pause_simulation ()
pauses the simulation
Definition at line 69 of file simulation_control.cc.
void SimulationControl::terminate_simulation ()
terminates simulation and cleans up the simulation thread
Definition at line 75 of file simulation_control.cc.
Referenced by create_new_simulation().
void SimulationControl::process_simulation ()
process the simulation: advances the processing time and calls the visualizer if there is one.
Definition at line 86 of file simulation_control.cc.
void SimulationControl::set_visualizer (boost::shared_ptr< Visualizer > visualizer)
supplies the control with a new visualizer.
The documentation for this class was generated from the following files:
src/SimulationControl/simulation_control.h
src/SimulationControl/simulation_control.cc