SynchronousASG Class Reference
The synchronous ASG produces a sequence of events according to the fully-synchronous time-model.
#include <synchronous_asg.h>
Public Member Functions
void initialize (const History &history, const vector< boost::shared_ptr< Robot > > &robots)
boost::shared_ptr< Event > get_next_event ()
int get_time_of_next_event ()
void update (const WorldInformation &world_information, boost::shared_ptr< Event > event)
Private Attributes
int time_of_next_event_
vector< boost::shared_ptr< const Request > > unhandled_request_set_
vector< boost::shared_ptr< Robot > > robots_
Static Private Attributes
static const int kTimeToLook = 0
static const int kTimeToCompute = 1
static const int kTimeToMove = 2
static const int kNumberOfEvents = 3
Detailed Description
The synchronous ASG produces a sequence of events according to the fully-synchronous time-model.
Definition at line 29 of file synchronous_asg.h.
Member Function Documentation
void SynchronousASG::initialize (const History & history, const vector< boost::shared_ptr< Robot > > & robots) [virtual]
initializes the synchronous ASG from the given intial world_state. Needs to be called before the ASG is used
Parameters:
The intial world state
Implements ActivationSequenceGenerator.
Definition at line 24 of file synchronous_asg.cc.
References robots_.
boost::shared_ptr< Event > SynchronousASG::get_next_event () [virtual]
Returns the next event. Since the ASG is synchronous the sequence of events will have the form of (look-compute-handle_requests)*. Each look and each compute event applies to every existing robot. In each handle_requests event all outstanding requests from the previous compute event is given to the event handler.
Returns: The next event in the sequence.
Implements ActivationSequenceGenerator.
Definition at line 32 of file synchronous_asg.cc.
References HandleRequestsEvent::add_to_requests(), ComputeEvent::add_to_robot_subset(), LookEvent::add_to_robot_subset(), robots_, time_of_next_event_, and unhandled_request_set_.
int SynchronousASG::get_time_of_next_event () [inline, virtual]
Returns the time of the next event. This is always the time of the last event plus one.
Returns: The time of the next event.
Implements ActivationSequenceGenerator.
Definition at line 53 of file synchronous_asg.h.
References time_of_next_event_.
void SynchronousASG::update (const WorldInformation & world_information, boost::shared_ptr< Event > event) [virtual]
Updates the sequence of events. For the synchronous ASG this only stores the requests of robots stored in compute events. The requests are added to the next handle_requests event.
Parameters:
A constant refrence to the newest world information
The last handled event
Implements SimulationListener.
Definition at line 68 of file synchronous_asg.cc.
References ComputeEvent::requests(), and unhandled_request_set_.
Member Data Documentation
int SynchronousASG::time_of_next_event_ [private]
The time the next event will happen.
Definition at line 68 of file synchronous_asg.h.
Referenced by get_next_event(), and get_time_of_next_event().
vector<boost::shared_ptr<const Request> > SynchronousASG::unhandled_request_set_ [private]
A set of unhandled requests from the last compute event.
Definition at line 73 of file synchronous_asg.h.
Referenced by get_next_event(), and update().
vector<boost::shared_ptr<Robot> > SynchronousASG::robots_ [private]
The set of all robots
Definition at line 78 of file synchronous_asg.h.
Referenced by get_next_event(), and initialize().
The documentation for this class was generated from the following files:
src/ActivationSequenceGenerators/synchronous_asg.h
src/ActivationSequenceGenerators/synchronous_asg.cc