WorldInformation Class Reference
Each WorldInformation instance corresponds to the state of the simulated world at a specific simulation step.
#include <world_information.h>
Public Member Functions
WorldInformation (const WorldInformation &rhs)
const vector< boost::shared_ptr< WorldObject > > & markers () const
vector< boost::shared_ptr< WorldObject > > & markers ()
void add_marker (boost::shared_ptr< WorldObject > new_marker)
const vector< boost::shared_ptr< Obstacle > > & obstacles () const
vector< boost::shared_ptr< Obstacle > > & obstacles ()
void add_obstacle (boost::shared_ptr< Obstacle > new_obstacle)
const vector< boost::shared_ptr< RobotData > > & robot_data () const
vector< boost::shared_ptr< RobotData > > & robot_data ()
void add_robot_data (boost::shared_ptr< RobotData > new_robot_data)
int time () const
void set_time (int time)
const RobotData & get_according_robot_data (boost::shared_ptr< RobotIdentifier > id) const
RobotData & get_according_robot_data (boost::shared_ptr< RobotIdentifier > id)
Private Attributes
std::vector< boost::shared_ptr< WorldObject > > markers_
std::vector< boost::shared_ptr< Obstacle > > obstacles_
std::vector< boost::shared_ptr< RobotData > > robot_data_
int time_
Detailed Description
Each WorldInformation instance corresponds to the state of the simulated world at a specific simulation step.
This class encapsulates information (as e.g. robot position, obstacles, ...) about the simulated world.
Note that this class provides 'const' as well as 'non-const' access most of its data members. In fact, one can think of it more as a struct than a class; the only possibly complex logic may be situated inside the more complex acccessor methods like 'get_according_robot_data'. The 'non-const' access is needed in the EventHandler to handle Request for a given robot. After the WorldInformation leaves the EventHandler only constant references/pointers to it will be accessible.
Author: Martina Hüllmann
Definition at line 33 of file world_information.h.
Member Function Documentation
const vector< boost::shared_ptr< WorldObject > > & WorldInformation::markers () const
Returns a constant reference to the set of the markers.
Returns: Constant reference to the set of the markers.
Definition at line 52 of file world_information.cc.
References markers_.
Referenced by EventHandler::extrapolate_old_world_information(), SphericView::init(), and OctreeView::init().
vector< boost::shared_ptr< WorldObject > > & WorldInformation::markers ()
Returns a (non-constant) reference to the set of markers.
Returns: reference to the set of markers.
Definition at line 56 of file world_information.cc.
References markers_.
void WorldInformation::add_marker (boost::shared_ptr< WorldObject > new_marker)
Adds a new marker to the world.
Parameters:
Shared pointer to the new marker.
Definition at line 60 of file world_information.cc.
References markers_.
const vector< boost::shared_ptr< Obstacle > > & WorldInformation::obstacles () const
Returns a constant reference to the set of the obstacles.
Returns: Constant reference to the set of the obstacles.
Definition at line 64 of file world_information.cc.
References obstacles_.
Referenced by EventHandler::extrapolate_old_world_information(), SphericView::init(), and OctreeView::init().
vector< boost::shared_ptr< Obstacle > > & WorldInformation::obstacles ()
Returns a (non-constant) reference to the set of obstacles.
Returns: reference to the set of obstacles.
Definition at line 68 of file world_information.cc.
References obstacles_.
void WorldInformation::add_obstacle (boost::shared_ptr< Obstacle > new_obstacle)
Adds a new obstacle to the world.
Parameters:
Shared pointer to the new obstacle.
Definition at line 72 of file world_information.cc.
References obstacles_.
const vector< boost::shared_ptr< RobotData > > & WorldInformation::robot_data () const
Returns a constant reference to the set of the robot data.
Returns: Constant reference to the set of the robots data.
Definition at line 76 of file world_information.cc.
References robot_data_.
Referenced by EventHandler::extrapolate_old_world_information(), SphericView::init(), and OctreeView::init().
vector< boost::shared_ptr< RobotData > > & WorldInformation::robot_data ()
Returns a (non-constant) reference to the set of robot data.
Returns: reference to the set of robot data.
Definition at line 80 of file world_information.cc.
References robot_data_.
void WorldInformation::add_robot_data (boost::shared_ptr< RobotData > new_robot_data)
Adds a new robot data to the world.
Parameters:
Shared pointer to the new robot data.
Definition at line 84 of file world_information.cc.
References robot_data_.
int WorldInformation::time () const
Returns the time (measured in steps) when this world info object was created.
Returns: Time (measured in steps) when this world info object was created.
Definition at line 88 of file world_information.cc.
References time_.
Referenced by EventHandler::extrapolate_old_world_information().
void WorldInformation::set_time (int time) [inline]
Setter for the time variable
Parameters:
the new time
Definition at line 107 of file world_information.h.
References time_.
const RobotData & WorldInformation::get_according_robot_data (boost::shared_ptr< RobotIdentifier > id) const
Return constant reference to according robotData of given robot ID
This method assumes, that the according reference to the robotData of a robot with ID i is saved at position i in the robot_datas-vector.
Parameters:
reference to identifier of robot whose robotData's reference shall be returned.
Returns: Constant reference to according robotData of given robot ID.
Definition at line 92 of file world_information.cc.
References robot_data_.
RobotData & WorldInformation::get_according_robot_data (boost::shared_ptr< RobotIdentifier > id)
Return (non-constant) reference to according robotData of given robot ID.
This method assumes, that the according reference to the robotData of a robot with ID i is saved at position i in the robot_datas-vector.
Parameters:
reference to identifier of robot whose robotData's reference shall be returned.
Returns: Mutable reference to according robotData of given robot ID.
Definition at line 97 of file world_information.cc.
References robot_data_.
Member Data Documentation
std::vector< boost::shared_ptr<WorldObject> > WorldInformation::markers_ [private]
Set of markers in the world
Definition at line 137 of file world_information.h.
Referenced by add_marker(), and markers().
std::vector< boost::shared_ptr<Obstacle> > WorldInformation::obstacles_ [private]
Set of obstacles in the world
Definition at line 142 of file world_information.h.
Referenced by add_obstacle(), and obstacles().
std::vector< boost::shared_ptr<RobotData> > WorldInformation::robot_data_ [private]
Set of robot datas of robots in the world
Definition at line 147 of file world_information.h.
Referenced by add_robot_data(), get_according_robot_data(), and robot_data().
int WorldInformation::time_ [private]
Time (measured in steps) of creation of this world information
Definition at line 152 of file world_information.h.
Referenced by set_time(), and time().
The documentation for this class was generated from the following files:
src/Model/world_information.h
src/Model/world_information.cc