RobotData Class Reference
Contains the properties a robot can have, but which are not necessarily visible to the robot and belong to the WorldInformation.
#include <robot_data.h>
Public Member Functions
RobotData (boost::shared_ptr< Identifier > id, boost::shared_ptr< Vector3d > position, const Robot &robot)
RobotData (boost::shared_ptr< Identifier > id, boost::shared_ptr< Vector3d > position, boost::shared_ptr< MarkerInformation > marker_information, const Robot &robot)
RobotData (const RobotData &rhs)
const Vector3d & acceleration () const
void set_acceleration (boost::shared_ptr< Vector3d > new_acceleration)
const boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > & coordinate_system_axis () const
void set_coordinate_system_axis (boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > new_axes)
const RobotType type () const
void set_type (RobotType type)
const Vector3d & velocity () const
void set_velocity (boost::shared_ptr< Vector3d > new_velocity)
boost::shared_ptr< Vector3d > extrapolated_position (double timesteps) const
boost::shared_ptr< Vector3d > extrapolated_velocity (double timesteps) const
RobotStatus status () const
void set_status (RobotStatus new_status)
const Robot & robot () const
virtual boost::shared_ptr< WorldObject > clone () const
Private Attributes
const Robot & robot_
boost::shared_ptr< Vector3d > acceleration_
boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > coordinate_system_axis_
RobotType type_
boost::shared_ptr< Vector3d > velocity_
RobotStatus status_
Detailed Description
Contains the properties a robot can have, but which are not necessarily visible to the robot and belong to the WorldInformation.
Author: Martina Hüllmann
Definition at line 34 of file robot_data.h.
Member Function Documentation
const Vector3d & RobotData::acceleration () const
Returns constant reference to acceleration vector of the robot.
Returns: Constant reference to acceleration vector of the robot.
Definition at line 42 of file robot_data.cc.
Referenced by extrapolated_position(), and extrapolated_velocity().
void RobotData::set_acceleration (boost::shared_ptr< Vector3d > new_acceleration)
Sets acceleration of the robot.
Parameters:
Pointer to acceleration vector.
Definition at line 46 of file robot_data.cc.
const boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > & RobotData::coordinate_system_axis () const
Returns constant reference to triple of pointers to vectors containing the coordinate system axis.
Returns: Triple of vectors containing the coordinate system axis.
Definition at line 51 of file robot_data.cc.
void RobotData::set_coordinate_system_axis (boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > new_axes)
Sets the coordinate system to the given triple of vectors.
Parameters:
Triple of vectors for new axes.
Definition at line 55 of file robot_data.cc.
const RobotType RobotData::type () const
Returns type of the robot.
Returns: type of the robot.
Definition at line 60 of file robot_data.cc.
void RobotData::set_type (RobotType type) [inline]
Sets the type of the robot.
Parameters:
new type
Definition at line 83 of file robot_data.h.
const Vector3d & RobotData::velocity () const
Returns constant reference to velocity vector of the robot.
Returns: constant reference Velocity vector of the robot.
Definition at line 64 of file robot_data.cc.
Referenced by extrapolated_position(), and extrapolated_velocity().
void RobotData::set_velocity (boost::shared_ptr< Vector3d > new_velocity)
Sets velocity of the robot.
Parameters:
Pointer to new velocity vector.
Definition at line 68 of file robot_data.cc.
boost::shared_ptr< Vector3d > RobotData::extrapolated_position (double timesteps) const
Returns position of the robot at the moment some timesteps in the future.
Parameters:
double for additional timesteps
Returns: Vector3d for coordinates
Definition at line 72 of file robot_data.cc.
References acceleration(), WorldObject::position(), and velocity().
boost::shared_ptr< Vector3d > RobotData::extrapolated_velocity (double timesteps) const
Returns velocity of the robot at the moment some timesteps in the future.
Parameters:
double for additional timesteps
Returns: Vector3d for coordinates
Definition at line 84 of file robot_data.cc.
References acceleration(), and velocity().
RobotStatus RobotData::status () const
Returns status of the robot.
Returns: Status of the robot.
Definition at line 92 of file robot_data.cc.
void RobotData::set_status (RobotStatus new_status)
Sets status of the robot.
Parameters:
new status
Definition at line 96 of file robot_data.cc.
const Robot & RobotData::robot () const
Returns reference to according robot-object.
Returns: Reference to according robot-object.
Definition at line 100 of file robot_data.cc.
References robot_.
boost::shared_ptr< WorldObject > RobotData::clone () const [virtual]
Clones this object and returns a shared ptr to the cloned object. typeid(*this) == typeid(*clone)
Returns: shared ptr to the cloned object
Reimplemented from WorldObject.
Definition at line 104 of file robot_data.cc.
Member Data Documentation
const Robot& RobotData::robot_ [private]
Reference to according robot.
Definition at line 134 of file robot_data.h.
Referenced by robot().
The documentation for this class was generated from the following files:
src/Model/robot_data.h
src/Model/robot_data.cc