SphericView Class Reference
Basic spherical view model.
#include <spheric_view.h>
Public Member Functions
SphericView (double view_radius)
void init (const WorldInformation &world_information)
Protected Member Functions
virtual std::set< RobotRef > get_visible_robots (const RobotData &robot) const
virtual std::set< ObstacleRef > get_visible_obstacles (const RobotData &robot) const
virtual std::set< MarkerRef > get_visible_markers (const RobotData &robot) const
double view_radius () const
Private Attributes
double view_radius_
Detailed Description
Basic spherical view model.
Provides implementations of getVisible... methods. To efficiently implement them the classes uses an Octree as internal data structure.
Assigning this class to a Robot corresponds to a `see all objects in a given radius` model.
Definition at line 25 of file spheric_view.h.
Member Function Documentation
void SphericView::init (const WorldInformation & world_information) [virtual]
Although init is trivial, it is nice to have a default constructor in virtual inherited classes. Otherwise every arbitrary deep sub class has to call the non-default constructor. Call this method before using any other method of View.
Parameters:
WorldInformation
Reimplemented from OctreeView.
Definition at line 24 of file spheric_view.cc.
References View::init(), WorldInformation::markers(), WorldInformation::obstacles(), and WorldInformation::robot_data().
The documentation for this class was generated from the following files:
src/Views/spheric_view.h
src/Views/spheric_view.cc