View Class Reference
Interface for Robot::compute() to the WorldInformation.
#include <view.h>
Public Member Functions
virtual void init (const WorldInformation &world_information)
const std::set< RobotRef > get_visible_robots (const Robot &caller) const
const std::set< ObstacleRef > get_visible_obstacles (const Robot &caller) const
const std::set< MarkerRef > get_visible_markers (const Robot &caller) const
const Vector3d get_position (const Robot &caller, WorldObjectRef world_object) const
const MarkerInformation get_marker_information (const Robot &caller, WorldObjectRef world_object) const
const std::size_t get_id (const Robot &caller, WorldObjectRef robot) const
const Vector3d get_robot_acceleration (const Robot &caller, RobotRef robot) const
const boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > get_robot_coordinate_system_axis (const Robot &caller, RobotRef robot) const
const RobotType get_robot_type (const Robot &caller, RobotRef robot) const
const Vector3d get_robot_velocity (const Robot &caller, RobotRef robot) const
const RobotStatus get_robot_status (const Robot &caller, RobotRef robot) const
const bool is_point_in_obstacle (ObstacleRef obstacle, const Vector3d &point) const
const double get_box_depth (BoxRef box) const
const double get_box_width (BoxRef box) const
const double get_box_height (BoxRef box) const
const double get_sphere_radius (SphereRef sphere) const
Protected Types
typedef boost::shared_ptr< RobotIdentifier > RobotRef
typedef boost::shared_ptr< ObstacleIdentifier > ObstacleRef
typedef boost::shared_ptr< BoxIdentifier > BoxRef
typedef boost::shared_ptr< SphereIdentifier > SphereRef
typedef boost::shared_ptr< MarkerIdentifier > MarkerRef
typedef boost::shared_ptr< Identifier > WorldObjectRef
Protected Member Functions
virtual std::set< RobotRef > get_visible_robots (const RobotData &robot) const
virtual std::set< ObstacleRef > get_visible_obstacles (const RobotData &robot) const
virtual std::set< MarkerRef > get_visible_markers (const RobotData &robot) const
virtual Vector3d get_own_position (const RobotData &robot) const
virtual Vector3d get_robot_position (const RobotData &robot) const
virtual Vector3d get_obstacle_position (const Obstacle &obstacle) const
virtual Vector3d get_marker_position (const WorldObject &marker) const
virtual MarkerInformation get_own_marker_information (const RobotData &robot) const
virtual MarkerInformation get_robots_marker_information (const RobotData &robot) const
virtual MarkerInformation get_obstacles_marker_information (const Obstacle &obstacle) const
virtual MarkerInformation get_markers_marker_information (const WorldObject &marker) const
virtual std::size_t get_own_id (const RobotData &robot) const
virtual std::size_t get_robot_id (const RobotData &robot) const
virtual std::size_t get_obstacle_id (const Obstacle &obstacle) const
virtual std::size_t get_marker_id (const WorldObject &marker) const
virtual Vector3d get_own_acceleration (const RobotData &robot) const
virtual Vector3d get_others_acceleration (const RobotData &robot) const
virtual boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > get_own_coordinate_system_axis (const RobotData &robot) const
virtual boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > get_others_coordinate_system_axis (const RobotData &robot) const
virtual RobotType get_own_type (const RobotData &robot) const
virtual RobotType get_others_type (const RobotData &robot) const
virtual Vector3d get_own_velocity (const RobotData &robot) const
virtual Vector3d get_others_velocity (const RobotData &robot) const
virtual RobotStatus get_own_status (const RobotData &robot) const
virtual RobotStatus get_others_status (const RobotData &robot) const
virtual bool is_point_in_obstacle (const Obstacle &obstacle, const Vector3d &point) const
virtual double get_box_depth (const Box &box) const
virtual double get_box_width (const Box &box) const
virtual double get_box_height (const Box &box) const
virtual double get_sphere_radius (const Sphere &sphere) const
const WorldInformation & world_information () const
const std::size_t get_id (boost::shared_ptr< Identifier > identifier) const
Private Member Functions
const Obstacle & resolve_obstacle_ref (ObstacleRef obstacle) const
const RobotData & resolve_robot_ref (RobotRef robot) const
const WorldObject & resolve_marker_ref (MarkerRef marker) const
const Box & resolve_box_ref (BoxRef box) const
const Sphere & resolve_sphere_ref (SphereRef sphere) const
const Obstacle & resolve_obstacle_ref_safe (ObstacleRef obstacle) const
const RobotData & resolve_robot_ref_safe (RobotRef robot) const
const WorldObject & resolve_marker_ref_safe (MarkerRef marker) const
const Box & resolve_box_ref_safe (BoxRef box) const
const Sphere & resolve_sphere_ref_safe (SphereRef sphere) const
template<typename T>
T delegate_function (boost::function< T(const View *, const RobotData &)> own_robot_fun, boost::function< T(const View *, const RobotData &)> other_robot_fun, boost::function< T(const View *, const Obstacle &)> obstacle_fun, boost::function< T(const View *, const WorldObject &)> marker_fun, const Robot &caller, WorldObjectRef world_object) const
template<typename T>
T delegate_function (boost::function< T(const View *, const RobotData &)> own_robot_fun, boost::function< T(const View *, const RobotData &)> other_robot_fun, const Robot &caller, RobotRef robot) const
Static Private Member Functions
static bool is_own_identifier (const Robot &robot, boost::shared_ptr< RobotIdentifier > identifier)
Private Attributes
const WorldInformation * world_information_
Detailed Description
Interface for Robot::compute() to the WorldInformation.
The View class represents the robots view to the world, i.e. a View class describes the information model that should be used for this simulation. This class is designed as a base class for more concrete models. Still there are no abstract methods. Instead, all methods are implemented such, that they throw a NotSupportedOperationException.
Note: Most methods specified in this class need to know the calling Robot, so they determine whether e.g. the own position is queried or the position of an other Robot.
Assigning this class to a Robot corresponds to a `no information at all` model for each Robot.
Definition at line 47 of file view.h.
Member Function Documentation
void View::init (const WorldInformation & world_information) [virtual]
Although init is trivial, it is nice to have a default constructor in virtual inherited classes. Otherwise every arbitrary deep sub class has to call the non-default constructor. Call this method before using any other method of View.
Parameters:
WorldInformation
Reimplemented in OctreeView, and SphericView.
Definition at line 118 of file view.cc.
Referenced by SphericView::init(), and OctreeView::init().
const std::set< View::RobotRef > View::get_visible_robots (const Robot & caller) const
Returns the set of robots visible for the calling Robot. Note: The Identifier of the calling Robot is never returned by this method.
Parameters:
Robot that should take a look-around
Returns: set of robots visible
Definition at line 123 of file view.cc.
const std::set< View::ObstacleRef > View::get_visible_obstacles (const Robot & caller) const
Returns the set of obstacles visible for the calling Robot.
Parameters:
Robot that should take a look-around
Returns: set of obstacles visible
Definition at line 129 of file view.cc.
const std::set< View::MarkerRef > View::get_visible_markers (const Robot & caller) const
Returns the set of markers visible for the calling Robot.
Parameters:
Robot that should take a look-around
Returns: set of markers visible
Definition at line 135 of file view.cc.
const Vector3d View::get_position (const Robot & caller, WorldObjectRef world_object) const
Queries for the position of a WorldObject identified by an given Identifier.
Parameters:
The Robot which is asking..
Identifier for a WorldObject
Returns: Position
See also: WorldObject::position()
Definition at line 140 of file view.cc.
References CoordConverter::global_to_local().
const MarkerInformation View::get_marker_information (const Robot & caller, WorldObjectRef world_object) const
Queries for the marker information of a WorldObject identified by an given Identifier.
Parameters:
The Robot which is asking..
Identifier for a WorldObject
Returns: MarkerInformation
See also: WorldObject::marker_information()
Definition at line 149 of file view.cc.
const std::size_t View::get_id (const Robot & caller, WorldObjectRef robot) const
Queries for the id of a WordObject identified by an given Identifier.
Parameters:
The Robot which is asking..
Identifier for a WorldObject
Returns: id
See also: WorldObject::id()
Definition at line 155 of file view.cc.
const Vector3d View::get_robot_acceleration (const Robot & caller, RobotRef robot) const
Queries for the acceleration of a Robot identified by an given RobotIdentifier.
Parameters:
The Robot which is asking..
RobotIdentifier
Returns: Vector3d
See also: RobotData::acceleration()
Definition at line 161 of file view.cc.
const boost::tuple< boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d >, boost::shared_ptr< Vector3d > > View::get_robot_coordinate_system_axis (const Robot & caller, RobotRef robot) const
Queries for the coordinate system axes of a Robot identified by an given RobotIdentifier.
Parameters:
The Robot which is asking..
RobotIdentifier
Returns: Vector3d
See also: RobotData::coordinate_system_axis()
Definition at line 165 of file view.cc.
const RobotType View::get_robot_type (const Robot & caller, RobotRef robot) const
Queries for the robot type of a Robot identified by an given RobotIdentifier.
Parameters:
The Robot which is asking..
RobotIdentifier
Returns: RobotType
See also: RobotData::type()
Definition at line 171 of file view.cc.
const Vector3d View::get_robot_velocity (const Robot & caller, RobotRef robot) const
Queries for the velocity of a Robot identified by an given RobotIdentifier.
Parameters:
The Robot which is asking..
RobotIdentifier
Returns: Vector3d
See also: RobotData::velocity()
Definition at line 175 of file view.cc.
const RobotStatus View::get_robot_status (const Robot & caller, RobotRef robot) const
Queries for the status of a Robot identified by an given RobotIdentifier.
Parameters:
The Robot which is asking..
RobotIdentifier
Returns: RobotStatus
See also: RobotData::status()
Definition at line 179 of file view.cc.
const bool View::is_point_in_obstacle (ObstacleRef obstacle, const Vector3d & point) const
Checks for a given point whether it is contained in a Obstacle identified by a given ObstacleIdentifier.
Parameters:
ObstacleIdentifier
point
Returns: true if point is contained in the obstacle; false, otherwise
See also: Obstacle::contains_point()
Definition at line 183 of file view.cc.
const double View::get_box_depth (BoxRef box) const
Queries for the depth of a Box identified by an given BoxIdentifier.
Parameters:
BoxIdentifier
Returns: depth
See also: Box::depth()
Definition at line 187 of file view.cc.
const double View::get_box_width (BoxRef box) const
Queries for the width of a Box identified by an given BoxIdentifier.
Parameters:
BoxIdentifier
Returns: width
See also: Box::width()
Definition at line 191 of file view.cc.
const double View::get_box_height (BoxRef box) const
Queries for the height of a Box identified by an given BoxIdentifier.
Parameters:
BoxIdentifier
Returns: height
See also: Box::height()
Definition at line 195 of file view.cc.
const double View::get_sphere_radius (SphereRef sphere) const
Queries for the radius of a Sphere identified by an given SphereIdentifier.
Parameters:
SphereIdentifier
Returns: radius
See also: Sphere::radius()
Definition at line 199 of file view.cc.
bool View::is_own_identifier (const Robot & robot, boost::shared_ptr< RobotIdentifier > identifier) [static, private]
Helper methods to check if the given Identifier points to the same data object as the given Robots Identifier does. To do so it compares the internal id of the Identifiers. (Thats also why this method is defined as class method (needs friend access)).
Definition at line 72 of file view.cc.
Referenced by delegate_function().
template<typename T> T View::delegate_function (boost::function< T(const View *, const RobotData &)> own_robot_fun, boost::function< T(const View *, const RobotData &)> other_robot_fun, boost::function< T(const View *, const Obstacle &)> obstacle_fun, boost::function< T(const View *, const WorldObject &)> marker_fun, const Robot & caller, WorldObjectRef world_object) const [inline, private]
Given a set of four methods this method decides which to call. This is used by View::get_position for example to delegate the call the View::get_own_position, View::get_robot_position, View::get_obstacle_position, and View::get_marker_position. Which method is called is decided as in View::get_own_position described.
The method uses resolve_*_ref_safe to resolve arguments for the given methods. A notable exception is the own_robot_function where resolve_robot_ref is used instead. This is because Identifier saved in Robot need not be same as saved in RobotData (pointerwise).
Definition at line 41 of file view.cc.
References is_own_identifier().
template<typename T> T View::delegate_function (boost::function< T(const View *, const RobotData &)> own_robot_fun, boost::function< T(const View *, const RobotData &)> other_robot_fun, const Robot & caller, RobotRef robot) const [inline, private]
Same as above except that this method only decides between two methods as needed for get_robot_* methods.
See also: View::delgate_function
Definition at line 62 of file view.cc.
References is_own_identifier().
The documentation for this class was generated from the following files:
src/Views/view.h
src/Views/view.cc