OctreeUtilities Class Reference
#include <octree_utilities.h>
Static Public Member Functions
static std::set< RobotRef > get_nearest_robots (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, const RobotRef &id, std::size_t num_nearest)
static std::set< MarkerRef > get_nearest_markers (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, std::size_t num_nearest)
static std::set< ObstacleRef > get_nearest_obstacles (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, std::size_t num_nearest)
static std::set< RobotRef > get_visible_robots_by_radius (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, float view_radius)
static std::set< MarkerRef > get_visible_markers_by_radius (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, float view_radius)
static std::set< ObstacleRef > get_visible_obstacles_by_radius (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, float view_radius)
Protected Types
typedef boost::shared_ptr< RobotIdentifier > RobotRef
typedef boost::shared_ptr< ObstacleIdentifier > ObstacleRef
typedef boost::shared_ptr< MarkerIdentifier > MarkerRef
Private Member Functions
OctreeUtilities ()
Static Private Member Functions
static void get_nearest_robots_Rec (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, std::size_t num_nearest, PriorityQueue< RobotRef >::Type &queue, const RobotRef &id)
static void get_nearest_markers_Rec (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, std::size_t num_nearest, PriorityQueue< MarkerRef >::Type &queue)
static void get_nearest_obstacles_Rec (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, std::size_t num_nearest, PriorityQueue< ObstacleRef >::Type &queue)
static void get_visible_robots_by_radius_Rec (const boost::shared_ptr< Octree > &octree, std::set< RobotRef > &robots_found, float sq_radius, const Vector3d &pos)
static void get_visible_markers_by_radius_Rec (const boost::shared_ptr< Octree > &octree, std::set< MarkerRef > &markers_found, float sq_radius, const Vector3d &pos)
static void get_visible_obstacles_by_radius_Rec (const boost::shared_ptr< Octree > &octree, std::set< ObstacleRef > &obstacles_found, float radius, const Vector3d &pos)
static bool compare_to_squared_radius (const boost::shared_ptr< Octree > &octree, const Vector3d &pos, float sq_radius)
static float calculate_squared_dist (const boost::shared_ptr< Octree > &octree, const Vector3d &pos)
Classes
struct PriorityQueue
class QueueEntry
Detailed Description
This Class adds some Methods for searching in the octree: * by maximal radius * k Nearest
Definition at line 36 of file octree_utilities.h.
Constructor & Destructor Documentation
OctreeUtilities::OctreeUtilities () [inline, private]
Do not allow any Objects of this type. So the constructor is private.
Definition at line 141 of file octree_utilities.h.
Member Function Documentation
std::set< OctreeUtilities::RobotRef > OctreeUtilities::get_nearest_robots (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, const RobotRef & id, std::size_t num_nearest) [static]
Returns the num_nearest robots relative to a point. To speed up the computation this works on the octree used by some View Objects.
Parameters:
octree The Octree in which all robots are saved.
pos The position for which to calculate the nearest robots
num_nearest The number of nearest robots to find
Returns: A set of Roboter Identifiers
Definition at line 229 of file octree_utilities.cc.
References get_nearest_robots_Rec().
std::set< OctreeUtilities::MarkerRef > OctreeUtilities::get_nearest_markers (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, std::size_t num_nearest) [static]
Returns the num_nearest robots relative to a point. To speed up the computation this works on the octree used by some View Objects.
Parameters:
octree The Octree in which all robots are saved.
pos The position for which to calculate the nearest markers
num_nearest The number of nearest markers to find
Returns: A set of Roboter Identifiers
Definition at line 359 of file octree_utilities.cc.
References get_nearest_markers_Rec().
std::set< OctreeUtilities::ObstacleRef > OctreeUtilities::get_nearest_obstacles (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, std::size_t num_nearest) [static]
Returns the num_nearest obstacles relative to a point. To speed up the computation this works on the octree used by some View Objects.
Parameters:
octree The Octree in which all robots are saved.
pos The position for which to calculate the nearest obstacles
num_nearest The number of nearest obstacles to find
Returns: A set of Obstacle Identifiers
Definition at line 486 of file octree_utilities.cc.
References get_nearest_obstacles_Rec().
std::set< OctreeUtilities::RobotRef > OctreeUtilities::get_visible_robots_by_radius (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, float view_radius) [static]
Returns the robots which have a distance to the point 'pos' at most view_radius. To speed up the computation this works on an octree used by some View Objects.
Parameters:
octree The octree to work on
pos The position to calculate the distance from
view_radius The maximal distance from the point pos
Returns: A set of Robot Identifiers.
Definition at line 53 of file octree_utilities.cc.
References get_visible_robots_by_radius_Rec().
std::set< OctreeUtilities::MarkerRef > OctreeUtilities::get_visible_markers_by_radius (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, float view_radius) [static]
Returns the markers which have a distance to the point 'pos' at most view_radius. To speed up the computation this works on an octree used by some View Objects.
Parameters:
octree The octree to work on
pos The position to calculate the distance from
view_radius The maximal distance from the point pos
Returns: A set of Marker Identifiers.
Definition at line 114 of file octree_utilities.cc.
References get_visible_markers_by_radius_Rec().
std::set< OctreeUtilities::ObstacleRef > OctreeUtilities::get_visible_obstacles_by_radius (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, float view_radius) [static]
Returns the obstacles which have a distance to the point 'pos' at most view_radius. To speed up the computation this works on an octree used by some View Objects.
Parameters:
octree The octree to work on
pos The position to calculate the distance from
view_radius The maximal distance from the point pos
Returns: A set of Obstacle Identifiers.
Definition at line 170 of file octree_utilities.cc.
References get_visible_obstacles_by_radius_Rec().
void OctreeUtilities::get_nearest_robots_Rec (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, std::size_t num_nearest, PriorityQueue< RobotRef >::Type & queue, const RobotRef & id) [static, private]
Does the real work for computing the nearest robots.
Parameters:
octree The octree to work on
pos The position to calculate the nearest robots for.
num_nearest The number of robots to find.
queue A Max Heap with the already found robots. New Robots will be added to this Heap.
id the id of the Robot, so we can distinguish the robot from the other
Definition at line 255 of file octree_utilities.cc.
Referenced by get_nearest_robots().
void OctreeUtilities::get_nearest_markers_Rec (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, std::size_t num_nearest, PriorityQueue< MarkerRef >::Type & queue) [static, private]
Does the real work for computing the nearest markers.
Parameters:
octree The octree to work on
pos The position to calculate the markers robots for.
num_nearest The number of markers to find.
queue A Max Heap with the already found markers. New markers will be added to this Heap.
Definition at line 384 of file octree_utilities.cc.
Referenced by get_nearest_markers().
void OctreeUtilities::get_nearest_obstacles_Rec (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, std::size_t num_nearest, PriorityQueue< ObstacleRef >::Type & queue) [static, private]
Does the real work for computing the nearest obstacles.
Parameters:
octree The octree to work on
pos The position to calculate the nearest obstacles for.
num_nearest The number of obstacles to find.
queue A Max Heap with the already found obstacles. New obstacles will be added to this Heap.
Definition at line 512 of file octree_utilities.cc.
Referenced by get_nearest_obstacles().
void OctreeUtilities::get_visible_robots_by_radius_Rec (const boost::shared_ptr< Octree > & octree, std::set< RobotRef > & robots_found, float sq_radius, const Vector3d & pos) [static, private]
Does the real Work on finding robots by radius.
Parameters:
octree The octree to work on
robots_found The set of already found robots. New found robots will be added to this set.
sq_radius The square of the view radius
pos The position of the robot
Definition at line 65 of file octree_utilities.cc.
References compare_to_squared_radius().
Referenced by get_visible_robots_by_radius().
void OctreeUtilities::get_visible_markers_by_radius_Rec (const boost::shared_ptr< Octree > & octree, std::set< MarkerRef > & markers_found, float sq_radius, const Vector3d & pos) [static, private]
Does the real Work on finding robots by radius.
Parameters:
octree The octree to work on
robots_found The set of already found robots. New found robots will be added to this set.
sq_radius The square of the view radius
pos The position of the robot
Definition at line 126 of file octree_utilities.cc.
References compare_to_squared_radius().
Referenced by get_visible_markers_by_radius().
void OctreeUtilities::get_visible_obstacles_by_radius_Rec (const boost::shared_ptr< Octree > & octree, std::set< ObstacleRef > & obstacles_found, float radius, const Vector3d & pos) [static, private]
Does the real Work on finding robots by radius.
Parameters:
octree The octree to work on
obstacles_found The set of already found obstacles. New found obstacles will be added to this set.
radius The view radius
pos The position of the robot
Definition at line 182 of file octree_utilities.cc.
References compare_to_squared_radius().
Referenced by get_visible_obstacles_by_radius().
bool OctreeUtilities::compare_to_squared_radius (const boost::shared_ptr< Octree > & octree, const Vector3d & pos, float sq_radius) [static, private]
Helper function to get rid of roots.
Definition at line 30 of file octree_utilities.cc.
Referenced by get_visible_markers_by_radius_Rec(), get_visible_obstacles_by_radius_Rec(), and get_visible_robots_by_radius_Rec().
float OctreeUtilities::calculate_squared_dist (const boost::shared_ptr< Octree > & octree, const Vector3d & pos) [static, private]
Helper function to get rid of roots.
Definition at line 42 of file octree_utilities.cc.
The documentation for this class was generated from the following files:
src/Views/octree_utilities.h
src/Views/octree_utilities.cc