Box Class Reference
Denotes an box-obstacle.
#include <box.h>
Public Member Functions
Box (boost::shared_ptr< Identifier > id, boost::shared_ptr< Vector3d > position, double depth, double width, double height)
Box (boost::shared_ptr< Identifier > id, boost::shared_ptr< Vector3d > position, boost::shared_ptr< MarkerInformation > marker_information, double depth, double width, double height)
double height () const
void set_height (double new_height)
double depth () const
void set_depth (double new_depth)
double width () const
void set_width (double new_width)
bool contains_point (boost::shared_ptr< Vector3d > point) const
virtual boost::shared_ptr< WorldObject > clone () const
Private Attributes
double depth_
double width_
double height_
Detailed Description
Denotes an box-obstacle.
Author: Martina Hüllmann
Definition at line 14 of file box.h.
Member Function Documentation
double Box::height () const
Returns the length of the box.
Returns: Length of the box.
Definition at line 22 of file box.cc.
Referenced by Octree::determine_obstacle_max_size().
void Box::set_height (double new_height)
Sets the height of the box to the given value.
Parameters:
New height of the box.
Definition at line 26 of file box.cc.
double Box::depth () const
Returns the depth of the box.
Returns: Depth of the box.
Definition at line 30 of file box.cc.
Referenced by Octree::determine_obstacle_max_size().
void Box::set_depth (double new_depth)
Sets the depth of the box to the given value.
Parameters:
New depth of the box.
Definition at line 34 of file box.cc.
double Box::width () const
Returns the width of the box.
Returns: Width of the box.
Definition at line 38 of file box.cc.
Referenced by Octree::determine_obstacle_max_size().
void Box::set_width (double new_width)
Sets the width of the box to the given value.
Parameters:
New width of the box.
Definition at line 42 of file box.cc.
bool Box::contains_point (boost::shared_ptr< Vector3d > point) const
Checks whether the given point is contained in the obstacle.
Parameters:
Pointer to vector of point to check whether it's contained in the obstacle.
Definition at line 51 of file box.cc.
boost::shared_ptr< WorldObject > Box::clone () const [virtual]
Clones this object and returns a shared ptr to the cloned object. typeid(*this) == typeid(*clone)
Returns: shared ptr to the cloned object
Reimplemented from WorldObject.
Definition at line 46 of file box.cc.
The documentation for this class was generated from the following files:
src/Model/box.h
src/Model/box.cc