Octree Class Reference
Implements an Octree for WorldObjects.
#include <octree.h>
Public Types
enum OctreeNodes {
TOP_LEFT_FRONT,
TOP_LEFT_BACK,
TOP_RIGHT_BACK,
TOP_RIGHT_FRONT,
BOTTOM_LEFT_FRONT,
BOTTOM_LEFT_BACK,
BOTTOM_RIGHT_BACK,
BOTTOM_RIGHT_FRONT
 }
Gives Names to Child Nodes of the octree instead of numeric values.
Public Member Functions
Octree ()
Set up the Octree Node.
Octree (int max_levels)
Octree (float min_width)
Octree (int max_levels, float min_width)
Set up the Octree Node.
void destroy_octree ()
void scene_dimensions (const std::vector< boost::shared_ptr< WorldObject > > &markers, const std::vector< boost::shared_ptr< Obstacle > > &obstacles, const std::vector< boost::shared_ptr< RobotData > > &robot_datas)
This sets the initial width, height and depth for the whole scene.
Vector3d new_node_center (Vector3d center, float width, int node_id)
This Method calculates the new center point of a node.
void create_node (const std::vector< boost::shared_ptr< WorldObject > > &markers, const std::vector< boost::shared_ptr< Obstacle > > &obstacles, const std::vector< boost::shared_ptr< RobotData > > &robot_datas, const Vector3d center, float width)
void create_new_node (const std::vector< boost::shared_ptr< WorldObject > > &markers, const std::vector< boost::shared_ptr< Obstacle > > &obstacles, const std::vector< boost::shared_ptr< RobotData > > &robot_datas, Vector3d center, float width, int node_id)
This creates a new node.
void create_tree (const std::vector< boost::shared_ptr< WorldObject > > &markers, const std::vector< boost::shared_ptr< Obstacle > > &obstacles, const std::vector< boost::shared_ptr< RobotData > > &robot_datas)
This is the starting point of the tree creation.
float calculate_dist_to_node (const Vector3d &pos) const
Calculates the distance to this node from a given point.
int point_in_node (const Vector3d &pos)
bool does_obstacle_fit (boost::shared_ptr< Obstacle > &obstacle) const
void assign_objects_to_node (const std::vector< boost::shared_ptr< WorldObject > > &markers, const std::vector< boost::shared_ptr< Obstacle > > &obstacles, const std::vector< boost::shared_ptr< RobotData > > &robot_datas)
void add_marker_to_node (boost::shared_ptr< WorldObject > marker)
void add_obstacle_to_node (boost::shared_ptr< Obstacle > obstacle)
void add_robot_data_to_node (boost::shared_ptr< RobotData > robot_data)
std::vector< boost::shared_ptr< WorldObject > > & marker_information ()
std::vector< boost::shared_ptr< Obstacle > > & obstacles ()
std::vector< boost::shared_ptr< RobotData > > & robot_datas ()
void set_parent (Octree *parent)
Octree & parent ()
int level ()
Vector3d center () const
int object_count () const
float width () const
bool sub_divided () const
int max_levels ()
float min_width ()
const boost::shared_ptr< Octree > & child (int child_id)
Protected Member Functions
void set_level (int level)
void set_max_levels (int max_level)
void set_min_width (float min_width)
int determine_obstacle_type (const boost::shared_ptr< Obstacle > &obstacle) const
Helps to determin the type of an obstacle object.
float determine_obstacle_max_size (const boost::shared_ptr< Obstacle > &obstacle) const
Returns the maximum size of an obstacle.
Private Member Functions
void init_octree ()
Private Attributes
Octree * parent_
int level_
int max_levels_
float min_width_
bool sub_divided_
float width_
int object_count_
Vector3d center_
std::vector< boost::shared_ptr< WorldObject > > markers_
std::vector< boost::shared_ptr< Obstacle > > obstacles_
std::vector< boost::shared_ptr< RobotData > > robot_datas_
boost::shared_ptr< Octree > octree_nodes_ [8]
Friends
class OctreeUtilities
Detailed Description
Implements an Octree for WorldObjects.
Author: Kamil Swierkot TODO: Describe how to use this class....
Definition at line 30 of file octree.h.
Constructor & Destructor Documentation
Octree::Octree ()
Set up the Octree Node.
max_levels_ is set to 20000 and min_width_ is set to 0.
Definition at line 23 of file octree.cc.
References max_levels_, and min_width_.
Referenced by create_new_node().
Octree::Octree (int max_levels, float min_width)
Set up the Octree Node.
Parameters:
max_levels Used to set the maximum depth of the Octree
min_width Used to set the min_width of an octree node
Definition at line 45 of file octree.cc.
Member Function Documentation
void Octree::scene_dimensions (const std::vector< boost::shared_ptr< WorldObject > > & markers, const std::vector< boost::shared_ptr< Obstacle > > & obstacles, const std::vector< boost::shared_ptr< RobotData > > & robot_datas)
This sets the initial width, height and depth for the whole scene.
Parameters:
markers The marker object in an vector of shared_ptr
obstacles The obstacles in an vector of shared_ptr
robot_datas The robot_datas in an vector of shared_ptr
Definition at line 97 of file octree.cc.
References center_, determine_obstacle_max_size(), obstacles(), robot_datas(), and width_.
Referenced by create_tree().
Vector3d Octree::new_node_center (Vector3d center, float width, int node_id)
This Method calculates the new center point of a node.
This takes in the previous nodes center, width and which node ID that will be subdivided. The Result is the center of the new node.
Parameters:
center The center of the parent node
width The width of the Octree Node box.
node_id The ID of the node
Definition at line 234 of file octree.cc.
References center().
Referenced by create_new_node(), and create_node().
void Octree::create_node (const std::vector< boost::shared_ptr< WorldObject > > & markers, const std::vector< boost::shared_ptr< Obstacle > > & obstacles, const std::vector< boost::shared_ptr< RobotData > > & robot_datas, const Vector3d center, float width)
This subdivides a node depending on the objects and node width
Parameters:
markers the markers to store in this subtree
obstacles the obstacles to store in this subtree
robot_datas the robot_datas to store in this subtree
center the center point of this node
width the width of this node
Definition at line 377 of file octree.cc.
References assign_objects_to_node(), center(), center_, create_new_node(), determine_obstacle_max_size(), level_, max_levels_, min_width_, new_node_center(), object_count(), object_count_, obstacles(), obstacles_, octree_nodes_, robot_datas(), sub_divided_, and width_.
Referenced by create_tree().
void Octree::create_new_node (const std::vector< boost::shared_ptr< WorldObject > > & markers, const std::vector< boost::shared_ptr< Obstacle > > & obstacles, const std::vector< boost::shared_ptr< RobotData > > & robot_datas, Vector3d center, float width, int node_id)
This creates a new node.
Parameters:
markers The Markers to be stored in this subtree
obstacles The obstacles to be stored in this subtree
robot_datas The robot datas to be stored in this subtree
center The center point of the new node
width the width of the bounding box
Definition at line 332 of file octree.cc.
References level_, max_levels_, min_width_, new_node_center(), obstacles(), Octree(), octree_nodes_, and robot_datas().
Referenced by create_node().
void Octree::create_tree (const std::vector< boost::shared_ptr< WorldObject > > & markers, const std::vector< boost::shared_ptr< Obstacle > > & obstacles, const std::vector< boost::shared_ptr< RobotData > > & robot_datas)
This is the starting point of the tree creation.
Parameters:
markers the markers to be stored in this tree
obstacles the obstacles to be stored in this tree
robot_datas the robot datas to be stored in this tree
Definition at line 877 of file octree.cc.
References center_, create_node(), obstacles(), robot_datas(), scene_dimensions(), and width_.
float Octree::calculate_dist_to_node (const Vector3d & pos) const
Calculates the distance to this node from a given point.
Parameters:
pos The position
Returns: Returns the distance to this node from the given point
Definition at line 756 of file octree.cc.
References center_, and width_.
int Octree::point_in_node (const Vector3d & pos)
Returns the index of the child node in which the point would belong to
Parameters:
pos The position of the point
Definition at line 825 of file octree.cc.
References center_.
bool Octree::does_obstacle_fit (boost::shared_ptr< Obstacle > & obstacle) const
Returns whether an obstacle would fit into this node or not
Parameters:
obstacle the obstacle
Definition at line 769 of file octree.cc.
References determine_obstacle_max_size().
void Octree::assign_objects_to_node (const std::vector< boost::shared_ptr< WorldObject > > & markers, const std::vector< boost::shared_ptr< Obstacle > > & obstacles, const std::vector< boost::shared_ptr< RobotData > > & robot_datas)
This method allows to add objects to the octree.
Parameters:
markers The new marker objects
obstacles The new obstacles
robot_datas The new robot_datas
Definition at line 888 of file octree.cc.
References markers_, obstacles(), obstacles_, robot_datas(), and robot_datas_.
Referenced by create_node().
void Octree::add_marker_to_node (boost::shared_ptr< WorldObject > marker)
This method allows to add a marker to this node
Parameters:
marker The marker to add to this node
Definition at line 897 of file octree.cc.
References markers_.
void Octree::add_obstacle_to_node (boost::shared_ptr< Obstacle > obstacle)
This method allows to add an obstacle to this node
Parameters:
obstacle The obstacle to add to this node
Definition at line 903 of file octree.cc.
References obstacles_.
void Octree::add_robot_data_to_node (boost::shared_ptr< RobotData > robot_data)
This method allows to add a robot data to this node
Parameters:
robot_data the new robot_data to add to this node
Definition at line 909 of file octree.cc.
References robot_datas_.
std::vector< boost::shared_ptr<WorldObject> >& Octree::marker_information () [inline]
Returns the marker stored in this node.
Definition at line 205 of file octree.h.
References markers_.
std::vector< boost::shared_ptr<Obstacle> >& Octree::obstacles () [inline]
Returns the obstacles stored in this node.
Definition at line 212 of file octree.h.
References obstacles_.
Referenced by assign_objects_to_node(), create_new_node(), create_node(), create_tree(), and scene_dimensions().
std::vector< boost::shared_ptr<RobotData> >& Octree::robot_datas () [inline]
Returns the robot datas stored in this node.
Definition at line 219 of file octree.h.
References robot_datas_.
Referenced by assign_objects_to_node(), create_new_node(), create_node(), create_tree(), and scene_dimensions().
void Octree::set_parent (Octree * parent) [inline]
This sets the parent of this node
Parameters:
parent A pointer to the parent of this node
Definition at line 228 of file octree.h.
References parent_.
Octree& Octree::parent () [inline]
Returns the parent of this node. This is node a boost::shared_ptr because the child nodes get destroyed before their parent.
Definition at line 237 of file octree.h.
References parent_.
int Octree::level () [inline]
Returns the depth of this node in the octree
Definition at line 244 of file octree.h.
References level_.
Vector3d Octree::center () const [inline]
This returns the center of this node
Definition at line 251 of file octree.h.
References center_.
Referenced by create_node(), and new_node_center().
int Octree::object_count () const [inline]
This return the number of objects which were stored in this node
Definition at line 258 of file octree.h.
References object_count_.
Referenced by create_node().
float Octree::width () const [inline]
This returns the width of this node (since it's a cube the height and depth are the same)
Definition at line 265 of file octree.h.
References width_.
bool Octree::sub_divided () const [inline]
This return whether the node is subdivided or not. If a node is subdivided, then it has all eight children.
Definition at line 274 of file octree.h.
References sub_divided_.
int Octree::max_levels () [inline]
Returns the maximal depth of this octree
Definition at line 280 of file octree.h.
References max_levels_.
float Octree::min_width () [inline]
Returns the minimal width of a node in this octree.
Definition at line 285 of file octree.h.
References min_width_.
const boost::shared_ptr<Octree>& Octree::child (int child_id) [inline]
Returns a child node.
Parameters:
child_id The number of the child. Values in between 0 and 7 are legal numbers
Definition at line 292 of file octree.h.
References octree_nodes_.
void Octree::set_level (int level) [inline, protected]
Sets the actual depth of this node.
Parameters:
level The depth of this node
Definition at line 302 of file octree.h.
References level_.
void Octree::set_max_levels (int max_level) [inline, protected]
Sets the max depth of the tree
Parameters:
max_level The maximal depth of the tree.
Definition at line 310 of file octree.h.
References max_levels_.
void Octree::set_min_width (float min_width) [inline, protected]
Sets the minimal width of a node.
Parameters:
min_width The minimal width of a node.
Definition at line 316 of file octree.h.
References min_width_.
int Octree::determine_obstacle_type (const boost::shared_ptr< Obstacle > & obstacle) const [protected]
Helps to determin the type of an obstacle object.
Parameters:
obstacle The obstacle to retrieve the real type of
Returns: The type of the obstacle: 1 Box, 2 Sphere
Definition at line 780 of file octree.cc.
Referenced by determine_obstacle_max_size().
float Octree::determine_obstacle_max_size (const boost::shared_ptr< Obstacle > & obstacle) const [protected]
Returns the maximum size of an obstacle.
Parameters:
obstacle the obstacle
Definition at line 792 of file octree.cc.
References Box::depth(), determine_obstacle_type(), Box::height(), Sphere::radius(), and Box::width().
Referenced by create_node(), does_obstacle_fit(), and scene_dimensions().
Member Data Documentation
Octree* Octree::parent_ [private]
this stores an pointer to its parent.
Definition at line 342 of file octree.h.
Referenced by parent(), and set_parent().
int Octree::level_ [private]
The depth of this node.
Definition at line 347 of file octree.h.
Referenced by create_new_node(), create_node(), level(), and set_level().
int Octree::max_levels_ [private]
The maximal depth of this tree
Definition at line 351 of file octree.h.
Referenced by create_new_node(), create_node(), max_levels(), Octree(), and set_max_levels().
float Octree::min_width_ [private]
The minimum size of an node
Definition at line 355 of file octree.h.
Referenced by create_new_node(), create_node(), min_width(), Octree(), and set_min_width().
bool Octree::sub_divided_ [private]
This tells whether the node has been subdivided or not. If this has been set to true, there won't be any robots and markers saved in this node
Definition at line 361 of file octree.h.
Referenced by create_node(), and sub_divided().
float Octree::width_ [private]
This is the size of the cube for this current node
Definition at line 366 of file octree.h.
Referenced by calculate_dist_to_node(), create_node(), create_tree(), scene_dimensions(), and width().
int Octree::object_count_ [private]
This holds the count of the objects in this node
Definition at line 371 of file octree.h.
Referenced by create_node(), and object_count().
Vector3d Octree::center_ [private]
This is the center of the node
Definition at line 377 of file octree.h.
Referenced by calculate_dist_to_node(), center(), create_node(), create_tree(), point_in_node(), and scene_dimensions().
std::vector< boost::shared_ptr<WorldObject> > Octree::markers_ [private]
Set of markers in the world
Definition at line 382 of file octree.h.
Referenced by add_marker_to_node(), assign_objects_to_node(), and marker_information().
std::vector< boost::shared_ptr<Obstacle> > Octree::obstacles_ [private]
Set of obstacles in the world
Definition at line 387 of file octree.h.
Referenced by add_obstacle_to_node(), assign_objects_to_node(), create_node(), and obstacles().
std::vector< boost::shared_ptr<RobotData> > Octree::robot_datas_ [private]
Set of robot datas of robots in the world
Definition at line 392 of file octree.h.
Referenced by add_robot_data_to_node(), assign_objects_to_node(), and robot_datas().
boost::shared_ptr<Octree> Octree::octree_nodes_[8] [private]
This are the links to the child nodes
Definition at line 398 of file octree.h.
Referenced by child(), create_new_node(), and create_node().
The documentation for this class was generated from the following files:
src/Views/octree.h
src/Views/octree.cc