OctreeView Class Reference
View sub class managing a octree.
#include <octree_view.h>
Public Member Functions
virtual void init (const WorldInformation &world_information)
Protected Member Functions
const boost::shared_ptr< Octree > & octree () const
Protected Attributes
boost::shared_ptr< Octree > octree_
Detailed Description
View sub class managing a octree.
This class is designed as a base class for view sub classes needing an octree.
Abstract class, because it makes no sense to assign this class to a Robot since the view model provided by this class is the same as by View.
Definition at line 26 of file octree_view.h.
Member Function Documentation
void OctreeView::init (const WorldInformation & world_information) [virtual]
Although init is trivial, it is nice to have a default constructor in virtual inherited classes. Otherwise every arbitrary deep sub class has to call the non-default constructor. Call this method before using any other method of View.
Parameters:
WorldInformation
Reimplemented from View.
Reimplemented in SphericView.
Definition at line 21 of file octree_view.cc.
References View::init(), WorldInformation::markers(), WorldInformation::obstacles(), and WorldInformation::robot_data().
The documentation for this class was generated from the following files:
src/Views/octree_view.h
src/Views/octree_view.cc